language: python

env:
 - DJANGO_VERSION=2.2.11
 - DJANGO_VERSION=3.0.4
 - DJANGO_VERSION=3.1

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO_VERSION=3.0.4
  - python: "3.5"
    env: DJANGO_VERSION=3.1

install:
 - pip install -q Django==$DJANGO_VERSION requests mock hypernova

script:
 - python runtests.py
