language: python

env:
 - DJANGO_VERSION=1.11.8
 - DJANGO_VERSION=2.2.8
 - DJANGO_VERSION=3.0.2

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.2.8
  - python: "pypy"
    env: DJANGO_VERSION=2.2.8
  - python: "3.7-dev"
    env: DJANGO_VERSION=1.11.8
  - python: "2.7"
    env: DJANGO_VERSION=3.0.2
  - python: "3.5"
    env: DJANGO_VERSION=3.0.2
  - python: "pypy"
    env: DJANGO_VERSION=3.0.2

install:
 - pip install -q Django==$DJANGO_VERSION requests mock

script:
 - python runtests.py
